package ircclient;

import java.awt.Color;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/**
 *
 * @author andrewtaylor
 */
public class InstantMessengerGUI extends javax.swing.JFrame {

    private Client client;
    private Color chatWindowBackgroundColor, 
                  chatWindowForegroundColor,
                  chatInputBackgroundColor, 
                  chatInputForegroundColor;
    private JFileChooser fileChooser;
    
    /**
     * Creates new form InstantMessengerGUI
     */
    public InstantMessengerGUI(Client client) {
        this.client = client;
        initComponents();
        fileChooser = new JFileChooser();
    }

    public void display(String message) {
        if (message.startsWith("PRIVMSG")) {
            chatWindow.append(client.getUserName() + ": " + message.split(" ")[2]);
        }
        else {
            chatWindow.append(message);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectDialog = new javax.swing.JDialog();
        hostnameLabel = new javax.swing.JLabel();
        hostnameTextField = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        colorsDialog = new javax.swing.JDialog();
        chatWindowBackgroundLabel = new javax.swing.JLabel();
        chatWindowForegroundLabel = new javax.swing.JLabel();
        chatInputBackgroundLabel = new javax.swing.JLabel();
        chatInputForegroundLabel = new javax.swing.JLabel();
        saveColorsButton = new javax.swing.JButton();
        chatWindowBackgroundColorButton = new javax.swing.JButton();
        chatWindowForegroundColorButton = new javax.swing.JButton();
        chatInputBackgroundColorButton = new javax.swing.JButton();
        chatInputForegroundColorButton = new javax.swing.JButton();
        chatWindowScrollPane = new javax.swing.JScrollPane();
        chatWindow = new javax.swing.JTextArea();
        userInputScrollPane = new javax.swing.JScrollPane();
        chatInputTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        connectMenuItem = new javax.swing.JMenuItem();
        disconnectMenuItem = new javax.swing.JMenuItem();
        colorsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        connectDialog.setSize(new java.awt.Dimension(492, 394));

        hostnameLabel.setText("Hostname:");

        portLabel.setText("Port:");

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout connectDialogLayout = new javax.swing.GroupLayout(connectDialog.getContentPane());
        connectDialog.getContentPane().setLayout(connectDialogLayout);
        connectDialogLayout.setHorizontalGroup(
            connectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectDialogLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(connectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectButton)
                    .addGroup(connectDialogLayout.createSequentialGroup()
                        .addGroup(connectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostnameLabel)
                            .addComponent(portLabel))
                        .addGap(39, 39, 39)
                        .addGroup(connectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hostnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(portTextField))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        connectDialogLayout.setVerticalGroup(
            connectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(connectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostnameLabel)
                    .addComponent(hostnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(connectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(connectButton)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        colorsDialog.setSize(new java.awt.Dimension(664, 315));

        chatWindowBackgroundLabel.setText("Chat window background:");

        chatWindowForegroundLabel.setText("Chat window foreground:");

        chatInputBackgroundLabel.setText("Chat input background:");

        chatInputForegroundLabel.setText("Chat input foreground:");

        saveColorsButton.setText("Save");
        saveColorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveColorsButtonActionPerformed(evt);
            }
        });

        chatWindowBackgroundColorButton.setText("Change color");
        chatWindowBackgroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatWindowBackgroundColorButtonActionPerformed(evt);
            }
        });

        chatWindowForegroundColorButton.setText("Change color");
        chatWindowForegroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatWindowForegroundColorButtonActionPerformed(evt);
            }
        });

        chatInputBackgroundColorButton.setText("Change color");
        chatInputBackgroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatInputBackgroundColorButtonActionPerformed(evt);
            }
        });

        chatInputForegroundColorButton.setText("Change color");
        chatInputForegroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatInputForegroundColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorsDialogLayout = new javax.swing.GroupLayout(colorsDialog.getContentPane());
        colorsDialog.getContentPane().setLayout(colorsDialogLayout);
        colorsDialogLayout.setHorizontalGroup(
            colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsDialogLayout.createSequentialGroup()
                .addGroup(colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorsDialogLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chatWindowBackgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chatWindowForegroundLabel)
                            .addComponent(chatInputBackgroundLabel)
                            .addComponent(chatInputForegroundLabel))
                        .addGap(28, 28, 28)
                        .addGroup(colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chatInputForegroundColorButton)
                            .addComponent(chatInputBackgroundColorButton)
                            .addGroup(colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chatWindowBackgroundColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chatWindowForegroundColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(colorsDialogLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(saveColorsButton)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        colorsDialogLayout.setVerticalGroup(
            colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsDialogLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatWindowBackgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chatWindowBackgroundColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatWindowForegroundLabel)
                    .addComponent(chatWindowForegroundColorButton))
                .addGap(18, 18, 18)
                .addGroup(colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatInputBackgroundLabel)
                    .addComponent(chatInputBackgroundColorButton))
                .addGap(15, 15, 15)
                .addGroup(colorsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatInputForegroundLabel)
                    .addComponent(chatInputForegroundColorButton))
                .addGap(18, 18, 18)
                .addComponent(saveColorsButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chatWindow.setColumns(20);
        chatWindow.setRows(5);
        chatWindowScrollPane.setViewportView(chatWindow);

        chatInputTextArea.setColumns(20);
        chatInputTextArea.setRows(5);
        userInputScrollPane.setViewportView(chatInputTextArea);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        connectMenuItem.setText("Connect");
        connectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(connectMenuItem);

        disconnectMenuItem.setText("Disconnect");
        disconnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(disconnectMenuItem);

        colorsMenuItem.setText("Colors");
        colorsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(colorsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(chatWindowScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatWindowScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(userInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectMenuItemActionPerformed
        connectDialog.setVisible(true);
    }//GEN-LAST:event_connectMenuItemActionPerformed

    private void colorsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorsMenuItemActionPerformed
        colorsDialog.setVisible(true);
    }//GEN-LAST:event_colorsMenuItemActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        String hostname = hostnameTextField.getText();
        int port = Integer.parseInt(portTextField.getText());
        connectDialog.setVisible(false);
        client.connect(hostname, port);
    }//GEN-LAST:event_connectButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        client.exit();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void chatWindowBackgroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatWindowBackgroundColorButtonActionPerformed
        chatWindowBackgroundColor = JColorChooser.showDialog(null, "Chat window background color", chatWindowBackgroundColor);
    }//GEN-LAST:event_chatWindowBackgroundColorButtonActionPerformed

    private void chatWindowForegroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatWindowForegroundColorButtonActionPerformed
        chatWindowForegroundColor = JColorChooser.showDialog(null, "Chat window foreground color", chatWindowForegroundColor);
    }//GEN-LAST:event_chatWindowForegroundColorButtonActionPerformed

    private void chatInputBackgroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatInputBackgroundColorButtonActionPerformed
        chatInputBackgroundColor = JColorChooser.showDialog(null, "Chat input background color", chatInputBackgroundColor);
    }//GEN-LAST:event_chatInputBackgroundColorButtonActionPerformed

    private void chatInputForegroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatInputForegroundColorButtonActionPerformed
        chatInputForegroundColor = JColorChooser.showDialog(null, "Chat input foreground color", chatInputForegroundColor);
    }//GEN-LAST:event_chatInputForegroundColorButtonActionPerformed

    private void saveColorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveColorsButtonActionPerformed
        chatWindow.setBackground(chatWindowBackgroundColor);
        chatWindow.setForeground(chatWindowForegroundColor);
        chatInputTextArea.setBackground(chatInputBackgroundColor);
        chatInputTextArea.setForeground(chatInputForegroundColor);
        colorsDialog.setVisible(false);
    }//GEN-LAST:event_saveColorsButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String message = chatInputTextArea.getText();
        client.send(message);
        display(message + "\n");
        chatInputTextArea.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        int returnVal = fileChooser.showSaveDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(file));
                String text = chatWindow.getText();
                bufferedWriter.write(text + "\n");
                bufferedWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(InstantMessengerGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {       
            File file = fileChooser.getSelectedFile();
            try {
                String text = new String(Files.readAllBytes(file.toPath()));
                chatWindow.setText(text);
            } catch (IOException ex) {
                Logger.getLogger(InstantMessengerGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void disconnectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectMenuItemActionPerformed
        client.disconnect();
    }//GEN-LAST:event_disconnectMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chatInputBackgroundColorButton;
    private javax.swing.JLabel chatInputBackgroundLabel;
    private javax.swing.JButton chatInputForegroundColorButton;
    private javax.swing.JLabel chatInputForegroundLabel;
    private javax.swing.JTextArea chatInputTextArea;
    private javax.swing.JTextArea chatWindow;
    private javax.swing.JButton chatWindowBackgroundColorButton;
    private javax.swing.JLabel chatWindowBackgroundLabel;
    private javax.swing.JButton chatWindowForegroundColorButton;
    private javax.swing.JLabel chatWindowForegroundLabel;
    private javax.swing.JScrollPane chatWindowScrollPane;
    private javax.swing.JDialog colorsDialog;
    private javax.swing.JMenuItem colorsMenuItem;
    private javax.swing.JButton connectButton;
    private javax.swing.JDialog connectDialog;
    private javax.swing.JMenuItem connectMenuItem;
    private javax.swing.JMenuItem disconnectMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel hostnameLabel;
    private javax.swing.JTextField hostnameTextField;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JButton saveColorsButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton sendButton;
    private javax.swing.JScrollPane userInputScrollPane;
    // End of variables declaration//GEN-END:variables
}
